language: node_js
node_js: "lts/*"
cache: yarn
install:
    - yarn
    - yarn global add codecov
script:
    - yarn run lint
    - yarn test -- --coverage
    - codecov
    - yarn run build_examples
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: examples/build/
    on:
        branch: master
